version: "3"
services:
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  odoo:
    image: docker-odoo
    container_name: docker-odoo
    mem_limit: 2000000000
    privileged: true
    hostname: docker-odoo
    volumes:
      # custom addon folder
      - /home/ubuntu/code/custom/openeducat_erp/:/odoo/custom/addons
    ports:
      - "6169:6069"
      - "6122:22"
    # depends_on:
    #   - db
    links:
      - wdb
    environment:
      WDB_SOCKET_SERVER: wdb
      #WDB_NO_BROWSER_AUTO_OPEN: true
  wdb:
    image: kozea/wdb
    init: true
    ports:
      - "6184:1984"
