version: "2"
services:
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  odoo:
    image: docker-odoo
    container_name: docker-odoo
    mem_limit: 2000000000
    privileged: true
    restart: always
    hostname: docker-odoo
    volumes:
      # custom addon folder
      - /home/ubuntu/code/custom/openeducat_erp/:/home/odoo/custom/addons
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "6169:6069" # Odoo
      - "6155:5555" #debug
      - "6122:22" # ssh
volumes:
  postgres-data:
    external: false
