version: "3"
services:
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  odoo:
    image: docker-odoo
    container_name: docker-odoo
    mem_limit: 2000000000
    privileged: true
    hostname: docker-odoo
    # volumes:
    #   # - /home/ubuntu/code/docker-django/code:/home/docker/code
    ports:
      - "6169:6069"
      - "6122:22"
    # depends_on:
    #   - db
