version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    # command: python3 manage.py runserver 0.0.0.0:9000
    volumes:
      - /home/ubuntu/code/docker-django/code:/home/docker/code
    ports:
      - "9000:9000"
      - "9022:22"
    depends_on:
      - db
